name: walkthrough_animation
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.0.3
  build_runner: ^2.3.2


flutter_gen: 
  output: lib/assets/
  integrations: 
    flutter_svg: true
  line_length: 80

flutter: 
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true
